### PR TITLE
The generator is now in a separate package.

### PR DESCRIPTION
**Pull request by solher**
This is a fix of the pull request https://github.com/yvasiyarov/swagger/pull/76 about being able to use the generator from another package.

It worked when I tested it but it doesn't build anymore. The generator must be in a separate package (can't be in main).

Sorry about that.

### CODE REVIEW

**Comment by RobertJGabriel** [comment]
Awesome Stuff I was just about to make a pr about this. :+1: 

Also @yvasiyarov Do you think its worth creating a branch to begin development on a version that supports swagger 2.0 api guide lines ?

I have been working that the last few weeks :)

**Comment by yvasiyarov** [comment]
@solher merged, thanks a lot!
@RobertJGabriel yes, for sure. Please, send me your code in separate pull request. I will merge it into swagger 2.0 branch

**Comment by boonep** [comment]
This pull request changed all instances of "yvasiyarov" in the README.md to "solher".  Might want to revert.  Thanks!

**Comment by yvasiyarov** [comment]
@solher your pull request reverted. Please, change all references back to yvasiyarov

**Pull request merged**
