### PR TITLE
Swagger 2.0 Support (Start)

### PR DESCRIPTION
**Pull request by RobertJGabriel**
@yvasiyarov Currently testing it , so will be ready tomorrow.

But starts support for the swagger 2.0

### CODE REVIEW

**Comment by RobertJGabriel** [comment]
Going to fix the conflicts in the morning :)

**Comment by RobertJGabriel** [comment]
@yvasiyarov Good to go, needs more work. But with more people on it will get done faster :P

**Comment by yvasiyarov** [comment]
@RobertJGabriel merged!

**Comment by RobertJGabriel** [comment]
@yvasiyarov thank you :)

**Pull request merged**
