### PR TITLE
FIX parser fails on empty comments

### PR DESCRIPTION
**Pull request by szuecs**
I hope that's the right place, I just hacked the src without looking into it in more detail.
I always got the following error:

2015/03/23 14:37:50 Start parsing
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/yvasiyarov/swagger/parser.(*Operation).ParseComment(0xc20d4cdce0, 0xc208034bd8, 0x2, 0x0, 0x0)
        /home/sszuecs/go/src/github.com/yvasiyarov/swagger/parser/operation.go:56 +0xc59
github.com/yvasiyarov/swagger/parser.(*Parser).ParseApiDescription(0xc208054060, 0x7fffb93e3a06, 0x1b)
        /home/sszuecs/go/src/github.com/yvasiyarov/swagger/parser/parser.go:414 +0x4a8
github.com/yvasiyarov/swagger/parser.(*Parser).ParseApi(0xc208054060, 0x7fffb93e3a06, 0x1b)
        /home/sszuecs/go/src/github.com/yvasiyarov/swagger/parser/parser.go:222 +0x1f4
main.main()
        /home/sszuecs/go/src/github.com/yvasiyarov/swagger/generator.go:155 +0x69e

### CODE REVIEW

**Comment by drewwells** [comment]
Does this PR also fix your issue? https://github.com/yvasiyarov/swagger/pull/58

**Comment by szuecs** [comment]
Yes #58  also fix this issue, but I think it would make more sense to me to use #57, because swagger comments always are using @ as prefix so, do not care about these comments.
All the best, sandor

**Comment by drewwells** [comment]
Well it fails in either case empty lines causes the parser to access
invalid array element. Also they both should be ignored since they're
effectively the same thing ( no important annotation available on this line)

**Comment by szuecs** [comment]
Yes that's true. I hope we get one of them merged, soon.

**Comment by drewwells** [comment]
Me too, this is preventing us from using swagger .

**Comment by yvasiyarov** [comment]
#58 merged

**Pull request closed without merging**
